# Labels configuration
# Use with: npx github-label-sync --labels .github/labels.yml owner/repo
# Or: https://github.com/marketplace/actions/label-sync

# === TYPE ===
- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: enhancement
  color: "a2eeef"
  description: New feature or request

- name: task
  color: "0075ca"
  description: Discrete piece of work

- name: documentation
  color: "0075ca"
  description: Improvements or additions to docs

- name: question
  color: "d876e3"
  description: Further information requested

# === STATUS ===
- name: triage
  color: "fbca04"
  description: Needs review to determine priority/validity

- name: blocked
  color: "b60205"
  description: Waiting on something external

- name: in-progress
  color: "1d76db"
  description: Actively being worked on

- name: needs-review
  color: "5319e7"
  description: Ready for code review

- name: ready-to-merge
  color: "0e8a16"
  description: Approved and ready to merge

# === PRIORITY ===
- name: "priority: critical"
  color: "b60205"
  description: Must fix immediately

- name: "priority: high"
  color: "d93f0b"
  description: Important, fix soon

- name: "priority: medium"
  color: "fbca04"
  description: Normal priority

- name: "priority: low"
  color: "c5def5"
  description: Nice to have, no rush

# === SIZE ===
- name: "size: small"
  color: "c2e0c6"
  description: A few hours of work

- name: "size: medium"
  color: "fef2c0"
  description: 1-2 days of work

- name: "size: large"
  color: "f9d0c4"
  description: Several days of work

- name: "size: xl"
  color: "e99695"
  description: Should be broken down

# === SPECIAL ===
- name: "good first issue"
  color: "7057ff"
  description: Good for newcomers

- name: "help wanted"
  color: "008672"
  description: Extra attention needed

- name: duplicate
  color: "cfd3d7"
  description: This issue or PR already exists

- name: wontfix
  color: "ffffff"
  description: This will not be worked on

- name: security
  color: "b60205"
  description: Security-related issue
