name: Bug Report
description: Something isn't working as expected
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before you file
        - Search existing issues to avoid duplicates
        - Only one bug per issue

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly. What did you see?
      placeholder: "When I clicked X, Y happened instead of Z"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
      description: What was the correct behavior?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Exact steps someone else can follow to see the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this happen?
      options:
        - Every time
        - Sometimes (describe pattern if known)
        - Once
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, app version, device — whatever is relevant
      placeholder: |
        - Browser: Chrome 120
        - OS: macOS 14.2
        - App version: 2.1.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots / Screen recordings
      description: Paste error messages, attach screenshots, or link to recordings
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround (if any)
      description: Did you find a way around this?
    validations:
      required: false
