name: Feature Request
description: Suggest a new capability
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature requests are about problems, not solutions
        Tell us what you're trying to accomplish. We'll figure out the best way to solve it.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the situation. What are you trying to do? What's getting in your way?
      placeholder: "I'm trying to [goal], but currently I have to [painful workaround]"
    validations:
      required: true

  - type: textarea
    id: who
    attributes:
      label: Who has this problem?
      description: Is this just you, or have you heard from others? How often does this come up?
      placeholder: "This affects anyone who tries to..."
    validations:
      required: true

  - type: textarea
    id: current-workaround
    attributes:
      label: How do you handle this today?
      description: What's your current workaround? How painful is it?
    validations:
      required: true

  - type: textarea
    id: ideal-outcome
    attributes:
      label: What does success look like?
      description: If this were solved perfectly, what would you be able to do?
      placeholder: "A user can..."
    validations:
      required: true

  - type: textarea
    id: ideas
    attributes:
      label: Ideas (optional)
      description: If you have specific implementation ideas, share them — but we may solve it differently
    validations:
      required: false

  - type: dropdown
    id: urgency
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would make my life easier
        - Blocking me from using this effectively
        - Blocking my team/org from adopting this
    validations:
      required: true
